// <auto-generated />
using System;
using Bank.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Bank.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Bank.Domain.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Balance")
                        .HasColumnType("float");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Account");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c1acf3a0-cecd-4f5a-82b8-356805febe06"),
                            Balance = 3000.0,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("80e8fc35-48ae-41b3-962f-da4d1b64b444"),
                            Balance = 400000.0,
                            Type = 0
                        });
                });

            modelBuilder.Entity("Bank.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customer");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4e18e003-5fd2-438e-95c6-c8142166f7db"),
                            DateOfBirth = new DateTime(1993, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sam.johnes@gmail.com",
                            FirstName = "Sam",
                            LastName = "Johnes",
                            Password = "password",
                            UserName = "john"
                        });
                });

            modelBuilder.Entity("Bank.Domain.Entities.CustomerAccount", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CustomerId", "AccountId");

                    b.ToTable("CustomerAccount");

                    b.HasData(
                        new
                        {
                            CustomerId = new Guid("4e18e003-5fd2-438e-95c6-c8142166f7db"),
                            AccountId = new Guid("c1acf3a0-cecd-4f5a-82b8-356805febe06")
                        },
                        new
                        {
                            CustomerId = new Guid("4e18e003-5fd2-438e-95c6-c8142166f7db"),
                            AccountId = new Guid("80e8fc35-48ae-41b3-962f-da4d1b64b444")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
